/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'hongkailiu' at '24/04/16 4:41 PM' with Gradle 2.10
 *
 * @author hongkailiu, @date 24/04/16 4:41 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
